# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a673d8cc9bc683dc432e5460b4810ece70de551f418f1f0efdc13e94a450e57663c9b230db178bbf557068b0c5e9fee4cd4f07601e032bd2bac77ad7eea57190

test:
  secret_key_base: 1c7e1a934cf6f219cebc6f19b82b431a30fa6c94faccda58044131803ee132ccd0d8121e9bd8cdba0d332d23fa4cc47e2e0a9f807780eaf855265bf42355b5e8

# Do not keep production secrets in the repositories,
# instead read values from the environment.
production:
  secret_key_base: 1c7e1a934cf6f219cebc6f19b82b431a30fa6c94faccda58044131803ee132ccd0d8121e9bd8cdba0d332d23fa4cc47e2e0a9f807780eaf855265bf42355b5e8
